### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [arthurnn/minitest-emacs#23]
I'm using Spacemacs (just graduated from sublime text) which has it's own way to manually install packages. I figure out how to install it and I'm happy to contribute that in the Readme file. What is your protocol for contributions?

**Comment by arthurnn** [comment]
@renemaya ❤️  . Send a PR, and I can merge it. I dont use Spacemacs, so I have no idea how that setup looks like, I would love your contribution to improve the docs in that regard.

**Comment by gcentauri** [comment]
Seems like this has been addressed :)
