### ISSUE TITLE
fix files with test_ and test "" block

### ISSUE THREAD

**Issue by arthurnn** [arthurnn/minitest-emacs#8]
when having a file with both syntax:

``` ruby
def test_foo
end

test "bar" do
end
```

`C-c s` doesnt work as it will always look for `test ""` syntax first.

**Comment by gcentauri** [comment]
i can't seem to reproduce this, perhaps its been fixed?  I can't even seem to use the `test "foo" {}` syntax

**Comment by gcentauri** [comment]
This appears to be fixed with #47
